### PR TITLE
Make causcumber pip installable

### PR DESCRIPTION
**Pull request by bobturneruk**
when in the repo directory

```
git checkout pip
pip install -e .
```

(sorry bad branch name!)

### CODE REVIEW

**Comment by bobturneruk** [comment]
Currently failing on Windows 10 due to graphviz requirement.

**Comment by bobturneruk** [comment]
If it works on you machine `import causcumber.causcumber_utils` should be possible.

**Comment by jmafoster1** [comment]
I think it might be better to make the pip installable a separate repo. I know there'd only be one file in it at the moment, but it'd mean that folks wouldn't be cloning our experimental feature files to just install the basics. What do we think?

**Comment by jmafoster1** [comment]
Ah I see! That makes more sense, then, although I'm still in favour of 
separating our experimental data and case studies from code we want to 
distribute for people to use.

**Comment by bobturneruk** [comment]
Sorry. I was rushing and didn't explain properly.

Probably this warrants some discussion. Depends if the case studies become examples that serve to help people use the code. e.g. in [this repo](https://github.com/pykale/pykale) only the `kale/` folder is packaged.

**Comment by jmafoster1** [comment]
Yeah, that's fair. I'm in favour of including examples as part of the 
documentation.

**Comment by bobturneruk** [comment]
Hi @jmafoster1 - great to see commits going in! Are all of these related to the subject of this PR? If not, additional branches off main may be more appropriate in future.

**Comment by jmafoster1** [comment]
What's a PR?

They're all related to the pip aspect. I wanted to make an additional 
file with some generic step definitions part of the pip install and then 
had to fix a bunch of little bugs related to that.

**Comment by bobturneruk** [comment]
Sorry: Pull Request!

Great - makes complete sense what you're doing. Thanks!

**Pull request merged**
